---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - npm install --prefix stomskidotcomofficial
    - npm run build --prefix stomskidotcomofficial
    - /bin/cp -R stomskidotcomofficial/build/* $DEPLOYPATH
