---
deployment:
  tasks:
    - echo "Starting deployment process..."

    # Set the deployment path
    - export DEPLOYPATH=/home/mbxsybcv2dxh/public_html/
    - echo "Deployment path set to $DEPLOYPATH"

    # Deploy build directory contents
    - echo "Copying contents of build directory to deployment path..."
    - /bin/cp -R build/* $DEPLOYPATH
    - echo "Contents of build directory have been copied."

    - echo "Deployment process completed successfully."
